sudo: true
dist: bionic
language: cpp

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install -q gcc g++ cmake libeigen3-dev git wget valgrind
  - sudo apt-get install -q build-essential libssl-dev libffi-dev python3-dev python3-pip python3-setuptools
  - travis_wait pip3 install --user cpp-coveralls pytest wheel
  - git submodule update --init --recursive

script:
  - mkdir build
  - pushd build
  - cmake ..
  - cmake --build .
  - ./bin/unit_tests
  - popd
  - ./dev-scripts/runInstallPyPackage.sh # installs microgbtpy
  - pushd python-package && python3 -m pytest && popd

after_success:
  - coveralls --include src --include include --gcov-options '\-lp' --root .. --build-root .;

notifications:
  email: false
