sudo: true
dist: bionic
language: cpp

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install -q gcc g++ cmake libeigen3-dev git wget valgrind
  - sudo apt-get install -q build-essential libssl-dev libffi-dev python3-dev python3-pip
  - travis_wait pip install --user cpp-coveralls pytest
  - git submodule add -f https://github.com/pybind/pybind11.git # add pybind11 submodule
  - git submodule update --init --recursive

script:
  - mkdir build
  - pushd build
  - cmake ..
  - cmake --build .
  - valgrind --leak-check=full --track-fds=yes --track-origins=yes --leak-check=full --show-leak-kinds=all --error-exitcode=1 ./bin/unit_tests
  - ./bin/unit_tests
  - popd
  - ./dev-scripts/runInstallPyPackage.sh # install microgbtpy
  - pushd python-package && pytest && popd

after_success:
  - coveralls --include src --include include --gcov-options '\-lp' --root .. --build-root .;

notifications:
  email: false
