name: C++ Unit Testing

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install gcc deps
      run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - name: Install ubuntu deps
      run: sudo apt-get install -q gcc g++ cmake libeigen3-dev git wget python-dev
    - name: Install Python deps
      run: pip install --user --upgrade setuptools wheel pytest
    - name: build
      run: ./dev-scripts/runBuild.sh
    - name: cpp tests
      run: ./dev-scripts/runTests.sh
    - name: python tests
      run: ./dev-scripts/runPythonTests.sh
