name: C++ CI

on: [push]

jobs:
  unit-test-cpp-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install gcc deps
      run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - name: Install ubuntu deps
      run: sudo apt-get install -q gcc g++ cmake libeigen3-dev git wget build-essential libssl-dev libffi-dev python3-dev python3-pip python3-pytest python3-setuptools
    - name: Install Python deps
      run: pip3 install --user --upgrade wheel
    - name: build
      run: ./dev-scripts/runBuild.sh
    - name: cpp tests
      run: ./dev-scripts/runTests.sh

  unit-test-python-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install gcc deps
        run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - name: Install ubuntu deps
        run: sudo apt-get install -q gcc g++ cmake libeigen3-dev git wget build-essential libssl-dev libffi-dev python3-dev python3-pip python3-pytest python3-setuptools
      - name: Install Python deps
        run: pip3 install --user --upgrade wheel setuptools pip
      - name: Remove Python 2.7
        run: sudo apt-get remove --auto-remove python2.7
      - name: build
        run: ./dev-scripts/runBuild.sh
      - name: python unit test
        run: ./dev-scripts/runPythonTests.sh

  valgrind-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install gcc deps
        run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - name: Install ubuntu deps
        run: sudo apt-get install -q gcc g++ cmake libeigen3-dev git wget python-dev valgrind
      - name: Install Python deps
        run: pip install --user --upgrade setuptools wheel
      - name: build
        run: ./dev-scripts/runBuild.sh
      - name: valgrind - memory leaks
        run: ./dev-scripts/runValgrind.sh
