name: C/C++ CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install gcc deps
      run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - name: Install ubuntu deps
      run: sudo apt-get install -q gcc g++ cmake libeigen3-dev git wget python-dev valgrind
    - name: Install Python deps
      run: pip install --user cpp-coveralls setuptools wheels
    - name: build
      run: ./runBuild.sh
    - name: test
      run: cd build && ./bin/unit_tests

